name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        cpp-version: '17'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
    
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make
    
    - name: Run tests
      run: |
        cd build
        make test
    
    - name: Docker build
      run: docker build .
